language: node_js
node_js:
  - 10
before_install:
  - curl -o factorio.tar.gz -L https://www.factorio.com/get-download/latest/headless/linux64
  - tar -xf factorio.tar.gz
  - npm install -g codecov
script:
  - npm run-script ci-cover
  - cat temp/test/integration/log.txt
  - codecov -f coverage/lcov.info
